yonathan lukito
daring-fox-2019/mini-wp pull request #27
Opened 2019-05-13 01:41 UTC by yploekito

2019-05-13 01:45 UTC, yploekito commented
GCLOUD_PROJECT_ID = mini-wp-240006
CLOUD_BUCKET = yploekito
KEYFILE_PATH = keyfile.json
SECRET = nanti_pakai_env

2019-05-16 07:32 UTC, dmtrxw requested changes
Emang belom pake components ya?

2019-05-16 07:32 UTC, dmtrxw commented on server/package.json
> +    "dotenv": "^8.0.0",
`dotenv` itu `devDependencies`

2019-05-16 07:32 UTC, dmtrxw commented on server/.gitignore
> +.env
`.env` lu masih ke-upload

2019-05-16 07:32 UTC, closed without merging