template mini wp
daring-fox-2019/mini-wp pull request #3
Opened 2019-05-06 16:30 UTC by sukmaranggapradeta

2019-05-12 19:37 UTC, sukmaranggapradeta commented
1. masi ada bug kalo login pake google signin..hanya bisa view saja..
2. wysiwys ada kendala waktu gi gabung sama upload file imagenya..blum bisa resovle, jadinya ga dipake
3. kendala paling lama waktu upload file ke google cloud storage dan masalah google sign in

2019-05-13 01:55 UTC, sukmaranggapradeta commented
JWT_SECRET=kantongajaib
PROJECT_ID=gpc-upload-image
FILE_PATH=gpc-upload-image-a65161c7e335.json
ATLAS_URI=mongodb+srv://admin:admin@cluster0miniwp-5nrgs.gcp.mongodb.net/test?retryWrites=true
BUCKET_NAME=image-storage.sukmaranggapradeta.com
GOOGLE_CLIENT_ID=856869270081-kb2org181cjch32j6t631bc7hf40lggb.apps.googleusercontent.com
GOOGLE_CLIENT_SECRET=zgweMFtwtrIm3OKnO_xCCxWV
KEYFILE=gpc-upload-image-a65161c7e335.json

2019-05-16 07:03 UTC, dmtrxw requested changes

2019-05-16 07:03 UTC, dmtrxw commented on server/.gitignore
> +node_modules
`.env` dan file `*.json` yang ada private key harusnya di-ignore

2019-05-16 07:03 UTC, dmtrxw commented on server/middlewares/authorize.js
> +                console.log('cocok =======================')
`console.log` bekas testing jangan lupa dihapus, ngotor2in file dan makan proses

2019-05-16 07:03 UTC, dmtrxw commented on client/component/articleCard.js
> +        deleteArtikel(input){
Kalo pake bahasa inggris jangan separo2

2019-05-16 07:03 UTC, closed without merging